from .logs import setup_logging
from .settings import Settings

log = setup_logging(__name__)


def dummy_function(a: float, b: float, multiplier_factor: float = 1.0) -> float:
    """Run a dummy logic autogenerated by cookiecutter. Please replace this function."""
    return (a + b) * multiplier_factor


def main() -> None:
    """Run main application logic."""
    settings = Settings.build()

    log.info(f"[START] Starting execution. {settings=}")
    log.info(f"Result: {dummy_function(2, 2, settings.multiplier_factor)}")
    log.info("[END] Execution finished.")
